### ISSUE TITLE
Please make processCommunicator.write public

### ISSUE THREAD

**Issue by owagner** [calimero-project/calimero#15]
Currently, the ProcessCommunicator interface has methods for directly sending certain Java data types with appropriate conversion.

However, the method write(final GroupAddress dst, final Priority p, final DPTXlator t) is private. Making this method public, or adding a public method write(final GroupAddress dst,final DPTXlator t), would allow sending pre-translated data without having to duplicate the ASDU-preparing code.

**Comment by bmalinowsky** [comment]
I agree, thank you.
